/**
 * Lok'al Business Factory — AI Layer Type Contracts
 *
 * These types define the Mode Factory boundary:
 * ANY source (CLI, web form, API) → AIContext → Claude → GeneratedContent
 * The generators never know where the data came from.
 */

import type { BusinessType, HorarioBloque, Categoria, ThemePreset, FontStyle, LogoType } from "@/lib/factory/types";

// ─── What we send to Claude ───────────────────────────────────────

/** Minimum context Claude needs to generate authentic business content. */
export interface AIContext {
  nombre:            string;
  tipo:              BusinessType;
  ciudad:            string;
  /** Products/services from the catalog — names + optional prices for context. */
  servicios:         Array<{ nombre: string; precio?: number }>;
  /** Free-text story from the business owner. This is the key differentiator. */
  historia?:         string;
  /** What makes this business unique (owner's words). */
  diferenciadores?:  string;
}

// ─── BusinessDNA — strategic metadata for Lok'al platform ────────

/**
 * Strategic identity metadata generated by Claude.
 * Not used in the current UI — stored for future use:
 * semantic search, business matching, marketing recommendations,
 * Lok'al marketplace personalization.
 */
export interface BusinessDNA {
  archetype:        "tradicional" | "moderno" | "artesanal" | "premium" | "accesible" | "familiar";
  tone:             "cálido" | "profesional" | "juvenil" | "elegante" | "cercano" | "aspiracional";
  /** Who the business targets, 1 sentence max 80 chars. */
  audience:         string;
  /** Core differentiator, 1 sentence max 150 chars. */
  differentiation:  string;
  /** 5 semantic keywords for search/matching. */
  keywords:         [string, string, string, string, string];
}

// ─── What Claude returns ──────────────────────────────────────────

export interface GeneratedContent {
  /** Schema version — enables backward compatibility as business.ts evolves. */
  schemaVersion:   "1.0";

  lema:            string;  // max 80
  descripcion:     string;  // max 200
  menuEtiqueta:    string;  // max 40
  menuSubtitulo:   string;  // max 120

  valores: Array<{
    emoji:  string;
    titulo: string;         // max 20
    sub:    string;         // max 30
  }>;                       // exactly 4

  ctaHome: {
    titulo: string;         // max 50
    texto:  string;         // max 150
    boton:  string;         // max 30
  };

  itemNombre:    string;    // max 20
  footerSlogan:  string;    // max 80

  ui: {
    carritoVacio:  string;  // max 60
    ubicacionSub:  string;  // max 60
  };

  nosotros: {
    metaDescription:  string;   // max 160
    seccionLabel:     string;   // max 30
    heroTitulo:       string;   // max 60
    relato:           [string, string];  // exactly 2 paragraphs
    procesoTitulo:    string;   // max 50
    proceso: Array<{
      emoji:  string;
      titulo: string;           // max 30
      texto:  string;           // max 100
    }>;                         // exactly 3
    valoresTitulo:    string;   // max 30
    valores:          [[string, string], [string, string], [string, string], [string, string]];
    ctaTitulo:        string;   // max 50
  };

  /** Short descriptions for products that had none. Key = product name. */
  productDescriptions: Record<string, string>;

  /** Strategic identity metadata for Lok'al platform. */
  businessDNA: BusinessDNA;
}

// ─── Factual data — source-independent ───────────────────────────

/**
 * All factual, non-creative business data.
 * Collected by any input source (CLI, web form, API) independently of Claude.
 */
export interface ManualFactualData {
  nombre:          string;
  slug:            string;
  tipo:            BusinessType;
  logoLinea1:      string;
  logoLinea2:      string;
  emoji:           string;
  logoType:        LogoType;
  telefono:        string;
  whatsapp:        string;
  calle:           string;
  colonia:         string;
  ciudad:          string;
  cp:              string;
  lat:             number | null;
  lng:             number | null;
  horario:         HorarioBloque[];
  costoEnvioPesos: number;
  zonaCobertura:   string;
  categorias:      Categoria[];
  themePreset:     ThemePreset;
  primaryHex:      string | null;
  fontStyle:       FontStyle;
  mpDescriptor:    string;
}

// ─── Token usage (for cost reporting) ────────────────────────────

export interface TokenUsage {
  inputTokens:  number;
  outputTokens: number;
  costUSD:      number;
  model:        string;
}

// ─── AI generation result ────────────────────────────────────────

export interface GenerationResult {
  content:    GeneratedContent;
  usage:      TokenUsage;
  attempts:   number;
  fromFallback: boolean;
}
