/**
 * Canonical JSON types for the Lok'al Business Factory.
 *
 * These are the source-of-truth objects. Generators produce .ts files from them.
 * Designed for direct storage in Supabase JSONB columns (Sprint 5E):
 *   businesses.config  ← BusinessConfig
 *   businesses.theme   ← ThemeConfig
 *   businesses.dna     ← BusinessDNA (from ai/types.ts)
 *
 * Nota de estrategia (2026-06): el flujo principal de alta de negocios será
 * directo a businesses.config/.theme/.dna en la plataforma compartida (6D-C.2);
 * la exportación a ZIP queda clasificada como modo legacy/opcional, no como ruta principal.
 */

import type { BusinessInput } from "@/lib/factory/types";
import type { ThemeColors } from "@/lib/factory/types";
import type { BusinessDNA, GeneratedContent } from "@/lib/factory/ai/types";

// ─── ThemeConfig — serializable theme (no TypeScript constructs) ──

export interface ThemeConfig {
  schemaVersion: "1.0";
  colors:  ThemeColors;
  fonts:   { display: "fraunces" | "cormorant" };
  logo:    { type: "text" | "image" };
}

// ─── BusinessConfig — canonical business object ───────────────────

/** Same structure as BusinessInput but typed for DB storage. */
export type BusinessConfig = BusinessInput;

// ─── FactoryDraft — the complete onboarding session state ─────────

export interface FactoryDraft {
  schemaVersion: "1.0";
  slug:          string;
  /** Factual data and generated content — stored as businesses.config in DB. */
  businessConfig: BusinessConfig;
  /** Theme colors and typography — stored as businesses.theme in DB. */
  themeConfig:    ThemeConfig;
  /** AI-generated strategic metadata — stored as businesses.dna in DB. */
  businessDNA?:   BusinessDNA;
  /** The full AI-generated content (used for preview; not stored in DB long-term). */
  generatedContent?: GeneratedContent;
  /** Banner image as base64 data URL — stripped before DB storage. */
  bannerDataUrl?: string;
  /** Logo image as base64 data URL — stripped before DB storage. */
  logoDataUrl?:   string;
  /** When the draft was last modified. */
  lastModified:   string;
  /** Whether content was generated by Claude or template fallback. */
  fromAI:         boolean;
}

// ─── Step-by-step form state ──────────────────────────────────────

export type FactoryStep =
  | "identidad"
  | "contacto"
  | "ubicacion"
  | "horario"
  | "catalogo"
  | "historia"
  | "branding"
  | "resumen";

export const FACTORY_STEPS: FactoryStep[] = [
  "identidad", "contacto", "ubicacion", "horario",
  "catalogo", "historia", "branding", "resumen",
];

export const STEP_LABELS: Record<FactoryStep, string> = {
  identidad:  "Identidad",
  contacto:   "Contacto",
  ubicacion:  "Ubicación",
  horario:    "Horario",
  catalogo:   "Catálogo",
  historia:   "Historia",
  branding:   "Branding",
  resumen:    "Resumen",
};
